# Generated by Django 3.2.6 on 2022-01-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
